FIx CI error

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,19 +39,24 @@ jobs:
 
         
 
+          - name: Verify secrets
+            run: |
+             [ -n "$BASE_URL" ] && echo "BASE_URL Exist" || echo "BASE_URL Missing"
+             [ -n "$ADMIN_USER" ] && echo "ADMIN_USER Exist" || echo "ADMIN_USER Missing"
+             [ -n "$ADMIN_PASSWORD" ] && echo "ADMIN_PASSWORD" || echo "ADMIN_PASSWORD Missing"
+            
             #B4 cai browser co san cua playwright
             # --with-deps cai dat cac thu vien phu thuoc cua browser
-            env:
-             BASE_URL: ${{ secrets.BASE_URL }}
-             ADMIN_USER: ${{ secrets.ADMIN_USER }}
-             ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
           - name: Install playwright browsers
             run: npx playwright install --with-deps
 
             #B5 chay test
           - name: Run playwright test
             run: npx playwright test --workers=2
-
+            env:
+             BASE_URL: ${{ secrets.BASE_URL }}
+             ADMIN_USER: ${{ secrets.ADMIN_USER }}
+             ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
           - name: Upload Playwright report
             if: always()
             uses: actions/upload-artifact@v4
